### ISSUE TITLE
Error: Cannot find module 'Q'

### ISSUE THREAD

**Issue by lwojgithub** [owaspsamm/dashboard-webapp#1]
executed command in /server folder
npm install
npm install nodemon
npm start

> server@1.0.0 start /opt/samm/server
> node server.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'Q'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/samm/server/router/index.router.js:3:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

cd /server/node_modules/Q
cat README.md
# Deprecated Package

This package is no longer supported and has been deprecated. To avoid malicious use, npm is hanging on to the package name.

Please contact support@npmjs.com if you have questions about this package.

**Comment by mgillam** [comment]
https://github.com/OWASP/samm/blob/master/Supporting%20Resources/app/server/router/index.router.js#L3 seems to be this import. I don't see it in the `package.json`, not sure if it's been globally installed on the dev system.
Seems to match https://www.npmjs.com/package/q based on usage.
I'd suggest maybe an `npm install --save q` from within the `server` directory might fix this issue.
Going forward, probably a PR with an updated `package.json` to commit the fix.

**Comment by lwojgithub** [comment]
Hi,

I'd suggest maybe an npm install --save q from within the server directory might fix this issue <- not working
I also try npm install within /server catalog <- not working

Maybe instruction is not precisious?

my steps:
1. git clone https://github.com/owaspsamm/dashboard-webapp.git
2. navigate to /server directory and open command prompt and run the command:
npm install
npm install nodemon
After installation, run the command:
npm start (Do not close this terminal)
3. navigate to /server2 directory and open command prompt and run the command:
npm install
npm install nodemon
After installation, run the command:
npm start (Do not close this terminal)
4. to run the angular app, go to the parent directory /SAMM and run 
npm install -> ng serve in cmd. (Do not close this terminal)

**Comment by mgillam** [comment]
I'm not sure the project's history or where it lived before here. When I tried installing `q`, it changed to failing on the `async` package. So I ran an `npm install --save async` as well. That got me past the dependency errors. I didn't set up the DB, so that failed, but...
![image](https://user-images.githubusercontent.com/4037926/108272858-cad90d00-7140-11eb-9df6-a4eb18cf4f88.png)
Can you confirm?
I ran it with an `npm start` after.

**Comment by lwojgithub** [comment]
No, I got:

> server@1.0.0 start /opt/samm/Supporting Resources/app/server
> node server.js

internal/modules/cjs/loader.js:323
      throw err;
      ^

Error: Cannot find module '/opt/samm/Supporting Resources/app/server/node_modules/Q/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:315:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:818:27)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/samm/Supporting Resources/app/server/router/index.router.js:3:9)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/opt/samm/Supporting Resources/app/server/node_modules/Q/package.json',
  requestPath: 'Q'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/samm/.npm/_logs/2021-02-17T22_13_54_366Z-debug.log

what NodeJS / npm version are you using?

**Comment by mgillam** [comment]
I have node v14.15.4 and npm v7.5.3 .. but there were some package warnings as well, node v12.x would probably be a better choice in the near term if it can be made to work.

**Comment by mgillam** [comment]
I also cloned it from *this* repo, and from your directory structure it looks like you cloned from https://github.com/OWASP/samm.git
So I did a fresh clone of that repo. Then did the following:
`npm install`
`npm start` -- failed on module Q
`npm install --save q`
`npm start` -- failed on module async
`npm install --save async`
`npm start` -- worked up to DB error.

Then I reset by restoring the package.json and package-lock.json and rm -rf the node_modules, and repeated the steps on node 12, and that worked the same for me.

**Comment by lwojgithub** [comment]
did you run these commands in the / server directory ?

**Comment by mgillam** [comment]
Yeah, that's correct. I ran them in `/server`.

**Comment by Unknownl3** [comment]
Hi, have the same problem with module Q, tried:
```
So I did a fresh clone of that repo. Then did the following in /dashboard-webapp/server:
npm install
npm start -- failed on module Q
npm install --save q
npm start 
```
but there is still "Error: Cannot find module 'Q'". Any thoughts on what else to try? thx

**Comment by lwojgithub** [comment]
cd node_modules

ln -s q Q

cd ../models

ln -s User.js user.js

**Comment by satyendra22** [comment]
> I'm not sure the project's history or where it lived before here. When I tried installing `q`, it changed to failing on the `async` package. So I ran an `npm install --save async` as well. That got me past the dependency errors. I didn't set up the DB, so that failed, but...
> ![image](https://user-images.githubusercontent.com/4037926/108272858-cad90d00-7140-11eb-9df6-a4eb18cf4f88.png)
> Can you confirm?
> I ran it with an `npm start` after.

I'm getting exactly same error. do we have any solution for this? @mgillam @lwojgithub @dkefer

**Comment by mgillam** [comment]
To be clear, I'm not a maintainer of this project. I have verified that it's behaving the same way for me today as it was on Feb 17. Which is to be expected, since I hadn't set up the Db, and still haven't. The I believe the `Error connecting to Db` message is correct behavior for my context.

**Comment by satyendra22** [comment]
@mgillam thx for quick reply , did u fixed the issue as you mentioned because currently I'm getting exactly same issue.

**Comment by Joda-repo** [comment]
Hi @satyendra22, i have same problem but suggestions:
https://github.com/owaspsamm/dashboard-webapp/issues/1#issuecomment-780900118
and 
https://github.com/owaspsamm/dashboard-webapp/issues/1#issuecomment-875340098

help me + I have correct connection to a database so it should work fine

**Comment by Joda-repo** [comment]
> 
> 
> @mgillam thx for quick reply , did u fixed the issue as you mentioned because currently I'm getting exactly same issue.

Hi @satyendra22 comments:
https://github.com/owaspsamm/dashboard-webapp/issues/1#issuecomment-780900118
and
https://github.com/owaspsamm/dashboard-webapp/issues/1#issuecomment-875340098

helped me to fix that issue. 

P.S. conection to Db looks fine too.

**Comment by ghost** [comment]
saw a few issues on npm imports/requires for the server package Q was one of them, async missing was another one. I would expect that you would want to correct case on the requires vs having to give a symlink from Q -> q. Other module import case sensitivity seen on requiring ../models/users when the file name is in caps so should be ../models/Users(?) or renaming the file to lowercase...
